### ISSUE TITLE
Tree and gutter not updating after commit

### ISSUE THREAD

**Issue by nvanrees** [atom/git-diff#104]
After a commit. The diff colors remain in the gutter and tree.
Only updates after closing and reopening the file, or restarting Atom. Also happens in safe-mode.

Atom version 1.8.0
Git-diff 1.0.1
On Linux Mint 17.3 Cinnamon 64-bit

**Comment by merlijnbruijnes** [comment]
Any news about this issue? I have exactly the same problem.

**Comment by 50Wliu** [comment]
I believe this is a duplicate of atom/atom#11358 and has been fixed.
