### ISSUE TITLE
Style elements within text editors using the `atom-text-editor::shadow` selector or the `.atom-text-editor.less` file extension.If you want to target overlay elements, target them directly or as descendants of `atom-overlay` elements.

### ISSUE THREAD

**Issue by LiyouZhou** [atom/git-diff#120]
In styles/git-diff.less: Style elements within text editors using the `atom-text-editor::shadow` selector or the `.atom-text-editor.less` file extension.
If you want to target overlay elements, target them directly or as descendants of `atom-overlay` elements.

**Comment by 50Wliu** [comment]
Without more information, I'm going to assume that you manually installed `git-diff`.  Please uninstall it using `apm uninstall git-diff` from the command line.
