### ISSUE TITLE
Feature: Toggle between changes since last commit and changes since commit before last

### ISSUE THREAD

**Issue by brettz9** [atom/git-diff#122]
### Description

It'd be awesome to be able to toggle between a diff of changes since the last commit and a diff between the current state of changes and the commit before last.

I will often work on a branch and commit and push the changes to store my changes, but I frequently go back and amend the commit and force an overwriting of the branch.

When continuing to work on the partially-completed commit, I cannot use git-diff to see the recently modified lines made since I have already committed my recent work.

**Comment by a7madgamal** [comment]
I strongly +1 this
However, I suggest we make it more flexible and add an option to pick ANY commit from the history and temporarily 'dirtify' atom as if these changes are still not committed
I think of this every single time I work in a new branch

I'm so excited for this that I decided to create my first atom package to do it. I would love to hear your feedback on this and of course I can offer my help to implement it in this package

**Comment by a7madgamal** [comment]
in simple and basic points, here is the problem:
- I work on a feature branch
- finished a small and committable part of the feature in hand
- I like the diff colors of changed files and code, so I don't commit to keep my focus 👎 
- at some point I have to commit, when I do I lose all the colors 😢 

also in simple and basic points, a possible solution:
- I commit the hell out of my progress 👍 
- I right click the project(s), pick a commit from a 'git log' dialogue
- atom treats the diff of current state and this commit as uncommitted changes 🍡 
- we use a different set of colors for committed changes and actual uncommitted changes
- when I'm done. I pick HEAD or something and disable the extra diff
- I keep my insanity. no resitting, no amending and no force pushing 😲

**Comment by brantwedel** [comment]
A quick toggle between last commit and upstream branch would be a great first step.

**Comment by Kivylius** [comment]
This would make tracking changes since x-branch so much easier. +1 on this. Really need this in.

**Comment by dmaz** [comment]
sublime's gitgutter has the ability to compare against any commit, branch or origin.  this is reflected through your whole project...   so in atom the file tree view, gutter decorations and minimaps should reflect changes since the new chosen commit.   

Often when I start digging into a big multi file change I hold off committing just to keep my focus I the files that changed.  because of course, once I do commit all that nice information is gone fromt the editor.

**Comment by maxbrunsfeld** [comment]
This issue was moved to atom/atom#18000
