### ISSUE TITLE
Git shows every line has been altered. 

### ISSUE THREAD

**Issue by jackjameshoward** [atom/git-diff#127]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * [X] Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * [X] Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * [X] Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * [ ] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * [ ] Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages **(I didn't see this as being relivent)**

### Description

Whenever I clone a repo and make an edit to any file, git-diff shows that every line in the file has been delete and an equal number of lines has been replaced. If I git add/commit/push/pull/fetch/merge the result is always the same in atom; if I change anything in atom it decects every line has been altered.
![image](https://cloud.githubusercontent.com/assets/4273996/23510958/7aa5abbc-ff53-11e6-93b2-135a419fc259.png)
Curiosly if I check what was commited via git, it will accurate show that only one line has changed.

### Steps to Reproduce

1. git clone a repo
2. open Atom
3. add Project Folder (Ctrl+Shift+A), add cloned repo folder.
5. open any file from repo - for example index.html
6. change anything one a single line in file and save file
7. bottom right corner states +200, -200 lines (for example)
8. git add and git commit
9. git commit reads +1, -1 line chaged
10. atom now reads up to date. 
11. repeat steps 5 to 10 and the outcome never changes

**Expected behavior:** Atom should read +1, -1 lines changed

**Actual behavior:** Atom shows all lines in file removed and an equal number replaced. 

**Reproduces how often:** This occurs on a freash install of Atom and a newly cloned repo. 

### Versions
I have done a fresh install using the `atom-x64-windows.zip` package.
It was install on a USB drive on a pc with Windows 7. I have followed the flight manual for converting to portable mode e.g. move the `.atom` folder to the correct location. 
There are no user installed packages. 

atom --version
------------------------
Atom    : 1.14.4
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm --verison
---------------------
apm  1.15.3
npm  3.10.5
node 4.4.5 x64

**Comment by 50Wliu** [comment]
This is most likely because of your `core.autocrlf` settings in Git.  Try setting it to `false` and see if that changes anything.

**Comment by jackjameshoward** [comment]
That seemed to do the trick. Thanks @50Wliu

**Comment by 50Wliu** [comment]
Awesome, glad it worked!

**Comment by qwemaze** [comment]
Heyyy, it's not a solution, it's a workaround!
I expect the plugin to show diff just as `git diff` command does, why is it still not a thing?

**Comment by thomasjo** [comment]
> Heyyy, it's not a solution, it's a workaround!
> I expect the plugin to show diff just as git diff command does, why is it still not a thing?

It does work, and what you are referring to is *not* a workaround...

If you can reliably reproduce, then open a new issue with a *detailed* list of steps required to reproduce the problem, and also full details such as Atom version, output of `git --version` etc. It's practically impossible for us to help you based on your comment.

**Comment by GioLogist** [comment]
This is still happening to me, even with autocrlf set to false.
