### ISSUE TITLE
git-diff for Atom not working

### ISSUE THREAD

**Issue by leongaban** [atom/git-diff#135]
https://stackoverflow.com/questions/45065401/git-diff-for-atom-not-working

###Atom version 1.18.0

I have a brand new install of Atom and installed git-diff. Created a new reducers.js file which was added to a commit, then wrote some code, the code isn't displaying as new:

[![enter image description here][1]][1]

I'm expecting a Green highlight line on the right side with the line numbers, however nothing is showing up?

[![enter image description here][2]][2]

  [1]: https://i.stack.imgur.com/UUhqU.png
  [2]: https://i.stack.imgur.com/qP6bg.png

**Comment by agupta1989** [comment]
@leongaban did you find any solution for this ?
