### ISSUE TITLE
git-diff does not follow config for submodule ( ignore = dirty )

### ISSUE THREAD

**Issue by terrywh** [atom/git-diff#140]
### Description
git-diff does not follow config for submodule ( ignore = dirty )

### Steps to Reproduce

1. config a submodule ( ignore = dirty ), for example:
```
[submodule "deps/nghttp2"]
	path = deps/nghttp2
	url = https://github.com/nghttp2/nghttp2.git
	ignore = dirty
```

2. touch a new file in that submodule

**Expected behavior:** 
do not show update or new file add

**Actual behavior:** 
a new file was added and marked green

**Reproduces how often:**
always

### Versions
git-diff 1.3.6
Atom x64 1.19.0 (Windows)

**Comment by maxbrunsfeld** [comment]
We'd probably get this behavior for free if we stopped computing diffs using [libgit2](https://libgit2.org/) and started using the `git` executable instead, like the [github package](https://github.com/atom/github) does.

**Comment by maxbrunsfeld** [comment]
This issue was moved to atom/atom#18003
