### ISSUE TITLE
empty Unstaged Changes : repository is not open in Atom

### ISSUE THREAD

**Issue by flatmax** [atom/git-diff#143]
hi there,

When I click a file (in the unstaged changes list) to look at its changes, the "Unstaged Changes" tab opens but it is empty. It reports :
The repository for path is not open in Atom.

I am using :
git-diff@1.3.6
atom 1.21.1 x64

**Comment by rsese** [comment]
Thanks for the report!  I think this is a duplicate of https://github.com/atom/github/issues/1179 and has been fixed in https://github.com/atom/github/pull/1217.  The fix should be available in an upcoming release.

**Comment by rsese** [comment]
Oh also, the problem was related to files that had a space in the filename or path to the filename - if that's not the case for you, please open a new issue in https://github.com/atom/github and fill out the issue template and we'll take a look.
