### ISSUE TITLE
Git diff showing all file as untracked file when not is.

### ISSUE THREAD

**Issue by sveracarrasco** [atom/git-diff#16]
Git diff show all the files of my repo like untracked files.

For example, If I add a new line to the file, the new line added isn't marked as "new line".

Screenshoots:

Before add a line
![image](https://cloud.githubusercontent.com/assets/5871371/2683333/47e16d4c-c1a8-11e3-9438-4bc07a8e5034.png)

After add a line

![image](https://cloud.githubusercontent.com/assets/5871371/2683345/597111f2-c1a8-11e3-8f5c-ffd7ee174317.png)

**Comment by dinosaurfiles** [comment]
+1 on this
https://i.imgur.com/rqaG4GC.png
https://i.imgur.com/OhPQolB.png

**Comment by maxbrunsfeld** [comment]
A lot has changed since we've heard about this happening, so the issue  may have been fixed. If not, please feel free to open a new issue on [the main Atom repository](https://github.com/atom/atom), as we have [moved this code there](https://github.com/atom/atom/pull/17993). Thanks!
