### ISSUE TITLE
Can't see indicators with Shadow DOM enabled

### ISSUE THREAD

**Issue by dmnd** [atom/git-diff#44]
I have a problem that's probably my own: it doesn't repro in safe mode, so it must be due to some package I have installed.

The problem is that the green, yellow and red indicators do not appear in the gutter when I have Shadow DOM enabled. Inspecting the DOM, I see that the gutter still has `.git-line-added` on it. But there's no CSS rule that adds the border. Here's the CSS that gets applied in normal mode:

![image](https://cloud.githubusercontent.com/assets/4427/5638773/f50aa064-95c0-11e4-9e4a-833a6060ef3f.png)

In safe mode, there is another rule that adds a green border.

![image](https://cloud.githubusercontent.com/assets/4427/5638785/1d872d82-95c1-11e4-9158-0257a45e1003.png)

I could understand if a package was overriding this rule, but somehow something I have installed seems to be preventing the rule from even being applied to the document. Any tips on debugging this?

I already tried disabling all my packages, but it didn't help.

**Comment by kevinsawicki** [comment]
Does it happen when you use a built-in theme?

**Comment by dmnd** [comment]
Yep, I'm using Atom Dark for both UI and syntax.

**Comment by kevinsawicki** [comment]
Hmm, not sure what to suggest besides disabling packages one at a time and seeing which one is causing it that way.

**Comment by dmnd** [comment]
I did try mass-disabling all my packages, but it didn't seem to help.

I was doing it quickly and probably made a mistake though. I'll try it
again when I have more time.

**Comment by kevinsawicki** [comment]
Just to check, do you have any bundled packages installed to `~/.atom/packages` or `~/.atom/dev/packages`?

If you had `git-diff` there then I could see this happening.

**Comment by benogle** [comment]
IIRC there were some packages that changed the styling of the gutter to not conflict with the git-diff. I think it was the linter? I cant remember though. I would find any package that puts something in the gutter, disable it and reload.

**Comment by lee-dohm** [comment]
@dmnd You might want to try @mark-hahn's [package-cop](https://github.com/mark-hahn/package-cop), it is designed specifically to help with this kind of `bisect` style search.

**Comment by dmnd** [comment]
@kevinsawicki is the winner :smile: 

I need to remember to `apm unlink` after working on packages...

**Comment by kevinsawicki** [comment]
> I need to remember to apm unlink after working on packages...

Yeah, when things go wrong for me the first command I run is `apm unlink -a`

**Comment by dmnd** [comment]
Thanks @lee-dohm I didn't realise a package bisector was released! I linked it from https://github.com/atom/atom/issues/2357.

I'll definitely `apm unlink -a` in the future. Thanks all!

**Comment by benogle** [comment]
> @kevinsawicki is the winner

Damn. I really wanted that new car

**Comment by dmnd** [comment]
> Damn. I really wanted that new car

:bike: is the best I can do for you
