### ISSUE TITLE
Package doesn't work for me on Mac os Yosemite Atom 0.174

### ISSUE THREAD

**Issue by armendarabyan** [atom/git-diff#45]
help me to make it work please.

**Comment by 50Wliu** [comment]
How is it not working?
Does it work in safe mode (`atom --safe`)?
Do you have the git-diff package enabled?

**Comment by armendarabyan** [comment]
just tried to run it with safe mode but no result.

git-diff is enabled, I even disabled and enabled it again, and it still doesn't work

**Comment by lee-dohm** [comment]
How are you launching Atom? Do you have the base of a Git repository open as the root of the project?

**Comment by glennlopez** [comment]
have the same problem.. i have to constantly untick and retick the "show icons in gutter" checkbox for the package to work.

**Comment by benogle** [comment]
My assumption is that it's working, but that the `show icons in gutter` option doesnt work anymore

**Comment by benogle** [comment]
Closing in favor of #46. If this is not the case, please comment.

**Comment by armendarabyan** [comment]
fixed on latest version
