### ISSUE TITLE
Support nested repos in non-repo project folder

### ISSUE THREAD

**Issue by oktayacikalin** [atom/git-diff#47]
Currently the gutter seems only to be working if the project root is a git repo. Please also support non-repo-root-folders with nested repos. I'm using this constellation at work because we have notes and other files which should not be in the (e.g. customer) repos.

**Comment by theblacklion** [comment]
Hmm.. this will be covered here, right? https://github.com/atom/atom/issues/2203

**Comment by lee-dohm** [comment]
@oktayacikalin Saw this on a clean-up pass I'm doing. Yes, atom/atom#2203 is where this will get resolved. I'll close this Issue as duplicate. You may want to subscribe to the other Issue for updates.
