### ISSUE TITLE
Incorrectly setting status-modified class for unmodified files

### ISSUE THREAD

**Issue by lieutdan13** [atom/git-diff#49]
I'm unable to pinpoint the cause of this bug, but it may possibly be an issue of file permissions. The "status-modified" class is applied to certain files, but when running "git status" via the command line, it shows no changes have been made.

My environment:
- Ubuntu 14.04
- Atom v0.178.0 installed via http://ppa.launchpad.net/webupd8team/atom/ubuntu trusty main
- Atom accessing files via a Samba share

**Comment by lieutdan13** [comment]
I'm sorry. Is this an issue with atom/git-utils as opposed to this repo?

**Comment by lee-dohm** [comment]
Given that you're accessing a Samba share, I'm assuming that you're sharing the files with Windows machines? If so, it could be a line ending issue. See #43 #26 and a few topics on [Discuss, the official Atom forum](https://discuss.atom.io).

**Comment by lieutdan13** [comment]
I'm glad you asked that, because the Samba share is actually between 2 Ubuntu machines and I just spent the entire day yesterday fixing line endings (some files were older and were originally developed on a Windows machine). Also, most of the files in question are images.

**Comment by lee-dohm** [comment]
Sorry to bring up a sore issue :wink: The other thing that I have seen cause issues are file mode changes, but yes, theoretically if `git status` isn't showing the files as modified then they shouldn't show that way in Atom either.

@izuzak ideas?

**Comment by lieutdan13** [comment]
No worries. It had been on my to do list for quite some time. I'm just glad I don't have to deal with the line ending discrepancies anymore.

Um...this issue appears to be intermittent. All looks good now. I reloaded and restarted Atom a few times. I changed my theme and then back again. I did NOT install any new packages or themes, nor did I change any settings in Atom. I've also opened up different projects and the issue seems to have been resolved. I will post here again if I see the issue show its face.

**Comment by Zeex** [comment]
I have a similar problem: files are shared via a common NTFS partition between two systems (Ubuntu and Windows), core.filemode is false.

After I've changed a few files and committed them from Windows git-diff shows all lines as modified in these files, but git status says there are not changes. I've already had `* text=auto` in my .gitattributes long before making these changes and line endings were already converted/normalized.

**Comment by thinklinux** [comment]
I'm having this problem too between Windows and Ubuntu. I will try to change core.filemode to false but searching the internet about that problem it seems it's not an atom bug. It's more of a git and samba bug. I've tested the new MS's editor and there is the same behavior :/

**Comment by gardiner** [comment]
I have the same issues with files which contain umlauts in their filename.
They are being marked as "new" in atom (and their parent directories are marked as "modified"), although they are already in the repository.

**Comment by maxbrunsfeld** [comment]
A lot has changed since we've heard about this happening, so the issue  may have been fixed. If not, please feel free to open a new issue on [the main Atom repository](https://github.com/atom/atom), as we have [moved this code there](https://github.com/atom/atom/pull/17993). Thanks!
