### ISSUE TITLE
Git diff only diffs when open folder has .git folder

### ISSUE THREAD

**Issue by eranimo** [atom/git-diff#55]
I opened a folder in Atom that has git-diff installed. This folder has several repos. Git diff appears to not be working, as if it was an untracked file.

**Comment by izuzak** [comment]
@eranimo Sounds related to https://github.com/atom/atom/issues/2203. Currently, Git-related features work if the root folder is the VCS root.

**Comment by MattKunze** [comment]
This also prevents the gutter from working when using git worktrees - in this case there is a `.git` file that points to master repo metadata, not a folder.

**Comment by kgunbin** [comment]
:+1: doesn't work in worktree

**Comment by joshaber** [comment]
Indeed, worktree support needs to be added to libgit2 before we can support it: https://github.com/libgit2/libgit2/issues/3159

**Comment by sangregoriopaolo** [comment]
+1

**Comment by washt** [comment]
+1

**Comment by JoshuaRogan** [comment]
+1

**Comment by lukecfairchild** [comment]
I know this issue is ancient, but this really needs to be done. +1

**Comment by maxbrunsfeld** [comment]
I'm not sure when we'll fix this, but you can subscribe to https://github.com/atom/atom/issues/2203 for updates on when we do. Sorry for the poor experience around this.
