### ISSUE TITLE
git-diff gutter not working

### ISSUE THREAD

**Issue by mattnorris** [atom/git-diff#59]
I tried all of the suggestions in [this thread](https://discuss.atom.io/t/git-diff-does-not-seem-to-be-working-at-all/5609), but gutters are not working. The thread itself is about *git-diff* not working at all. It is only the gutter functionality that is not working on my instance.

**Comment by lee-dohm** [comment]
Have you followed the suggestions in the [Debugging document](https://atom.io/docs/latest/hacking-atom-debugging)? Also, could you give the following information?

* Which version of Atom are you using?
* What OS and version are you running?
* Can you reproduce the issue after completely exiting Atom and restarting using `atom --safe`?
* Does this reproduce only with one Git repository? Or all Git repositories?

**Comment by mattnorris** [comment]
I did follow the document, tried `atom --safe`, and it was reproducible in multiple repositories. I ended up uninstalling Atom and reinstalling. `git-diff` is now working, but `git-blame` is not. 

Are there known issues with gutter packages? 

- 0.198.0 
- OS X Yosemite 10.10.3
- Yes
- All

**Comment by lee-dohm** [comment]
Not to my knowledge, no.

**Comment by mnquintana** [comment]
@mattnorris Just to make it a bit more explicit, what do you mean by the gutter "not working"? Are diffs not appearing at all? Are diffs sticking around after commits?

**Comment by mattnorris** [comment]
@mnquintana I was just inquiring if there were known issues with other packages that alter the gutter. I have since gotten `git-diff` to work but see that **Git Blame** is not working (although a friend says this is a known issue).
