### ISSUE TITLE
View diff

### ISSUE THREAD

**Issue by kaluznyo** [atom/git-diff#6]
Don't know if it's already possible, But can we see the diff, inline ? Instead just lines changed ?

**Comment by egorse** [comment]
+1

**Comment by janmarek** [comment]
Yes, what JetBrains have in their IDEs is great.

**Comment by theblacklion** [comment]
+1

**Comment by listepo** [comment]
+1

**Comment by peteruithoven** [comment]
The [Brackets git](https://github.com/zaggino/brackets-git) extention shows the difference in the following way after you click on the yellow or red bar in the cutter.
![screen shot 2015-06-13 at 15 48 08](https://cloud.githubusercontent.com/assets/523210/8144546/f9e82a62-11e3-11e5-8b02-6514c1f99826.png)
![screen shot 2015-06-13 at 15 48 18](https://cloud.githubusercontent.com/assets/523210/8144547/f9e92174-11e3-11e5-9253-9fb009fae9c7.png)
Pressing the *R* restores it.

**Comment by anjerodesu** [comment]
I think adding code glance would do the job. Mini map plugin has this feature (I mean "code glance" the line of code not the diff) so it should be possible to add it to git-diff.

**Comment by piotr-cz** [comment]
+1, this is really helpful in Brackets.io
Unfortunately I can't help here, coffee is not my cup of tea.

**Comment by nicolasmccurdy** [comment]
@samu :+1: for git-diff-details (thought it would also be nice to have a similar diff view in git-diff).

**Comment by piotr-cz** [comment]
git-diff-details has python as a decadency which is a no-go for me on windows

**Comment by pradyunsg** [comment]
+1

http://blog.atom.io/2016/02/03/introducing-block-decorations.html

If I read this correctly, it should be possible to utilizse this new API to show inline-diff! :smile:

**Comment by pablorsk** [comment]
+1

**Comment by samu** [comment]
Version `1.0.0` of the [git-diff-details](https://github.com/samu/git-diff-details ) package has been released today. Changes:

* now makes use of the new block decorators 
* dependency to `node-gyp` has been dropped, so there shouldn't be any problems with the installation any longer

**Comment by maxbrunsfeld** [comment]
This functionality is now provided by Atoms' builtin `github` package.
