### ISSUE TITLE
Diff for non-utf8 encoding file?

### ISSUE THREAD

**Issue by demon386** [atom/git-diff#60]
I have file encoded with GBK.

this plugin will marked lines with Chinese characters as diff, but the file actually doesn't have any diff.

![image](https://cloud.githubusercontent.com/assets/1246611/7782806/ee38f9cc-015c-11e5-92eb-c7c1821d9cc6.png)

**Comment by demon386** [comment]
@lee-dohm I inspect the code a little and this seems to be the bug of "getLineDiffs" ? seems that git-diff doesn't generate diff itself.

**Comment by lee-dohm** [comment]
No, git-diff depends on Atom Core libraries, which uses atom/git-utils, which ultimately relies on libgit2 to generate the diffs. Does Git actually provide an accurate diff if you just run it at the command line?

**Comment by demon386** [comment]
@lee-dohm git itself (command line) works fine.

I don't know how Atom Core libraries work. My guess is that for non-UTF8 file Atom transform it into UTF-8 in editor view?

**Comment by lee-dohm** [comment]
I don't know where the breakdown is exactly. Someone will have to investigate, I'm just narrowing things down :grinning:

**Comment by duub** [comment]
Happens the same with files having a filename with characters like the one in the screenshoot:

![screen shot 2015-06-13 at 11 22 59](https://cloud.githubusercontent.com/assets/2353096/8143797/9f1e7fd4-11be-11e5-9fb8-6c7e386c78f6.png)

**Comment by kracejic** [comment]
I also have this problem for iso885916 encoded files...

lines are marked as changed even when they are not.

**Comment by yzhong52** [comment]
As an workaround, I recommend change the encoding of the file to UTF-8.

**Comment by camlafit** [comment]
Hi

This problem is again here. UTF8 is not a workaround. 

On some case we can't use this charset. As example a bash script can't be encoded in utf8

**Comment by augusto-moura40** [comment]
The issue still exists.
In a file encoded with iso-8859-1, lines with accents (áãàâç) that are not modified are marked as modified.
I use GitKraken for git operations and it handles the file diff just fine.
![image](https://user-images.githubusercontent.com/22016397/36546119-518feff0-17c9-11e8-9a50-183f10883d75.png)

**Comment by maxbrunsfeld** [comment]
I would like to fix this, but I don't think we're likely to prioritize work on this anytime soon. I'm closing out old issues because we've [moved](https://github.com/atom/atom/pull/17993) this package into the main Atom repository. FWIW, This *is* something that we would most likely accept a PR for, if you submitted one that met our contributing guidelines. Thanks!
