### ISSUE TITLE
Feature Request: Click Gutter Icon to Scroll to Next Changed Block

### ISSUE THREAD

**Issue by woodrowbarlow** [atom/git-diff#63]
First of all, I've just started using Atom, so I'm not sure if this is possible or if it is within the scope of intended use for the gutter. If it is possible and desired behavior, I might try to go ahead and fork and pull it in when I get some free time.

Today I was looking for my change in a large file, and I tried clicking the "+1" in the corner of my atom window (the gutter icon), but it didn't work. So I checked the plugin preferences and saw that there was a keyboard shortcut to scroll to next changed block. I used that and it worked fine. Still, it would be intuitive to just be able to click on the gutter icon and scroll straight to the next change, or perhaps right click to get the three options (scroll to next, scroll to previous, show diff list) along with their keyboard shortcuts displayed next to them in a context menu.

Just posting here to see if this is possible, and if it would be desireable behavior.

**Comment by izuzak** [comment]
Hey @woodrowbarlow. Sorry for the delay in getting back to you on this. Just to make sure -- are you referring to the icons in the status bar (bottom right corner) and not the gutter? (+6, -3 in image below)

<img width="235" alt="screen shot 2015-08-22 at 09 52 59" src="https://cloud.githubusercontent.com/assets/38924/9423065/cb1d1da8-48b3-11e5-8477-e88c053a0caf.png">

If so, then that's implemented in the [status-bar package](https://github.com/atom/status-bar). I'm not strongly :+1: or :-1: on such a feature, but it's best to discuss it over there. Another option would be to show the list of diffs when you click that icon in the status bar (the same list you get when you execute the `Git Diff: Toggle Diff List` command from the command palette, which is similar to your right-click idea.

**Comment by woodrowbarlow** [comment]
Thank you for the follow-up. Yes, it seems I was confusing the status bar with the gutter. Thank you for pointing me in the right direction.
