### ISSUE TITLE
git status column not updated after partial staging

### ISSUE THREAD

**Issue by zonque** [atom/git-diff#66]
When all hunks in a file are commited, the colored status column is reset as expected. If, however, only some hunks are staged and commited (`git add -p` and friends), the update does not happen. Closing the tab and reopening fixes the issue.

**Comment by zonque** [comment]
Update: once the file is changed the first time after the commit, the update happens as well.

**Comment by izuzak** [comment]
Sorry for the delay in getting back to you on this, @zonque. Could you please provide exact steps which reproduce the problem, and also a GIF which demonstrates the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)? I just tried reproducing this and wasn't able to, so I'm wondering if I misunderstood the report or if this was fixed perhaps. In any case, providing all the relevant details (Atom version, OS version, reproducible in safe mode) and exact steps to reproduce + GIF is the best way to report problems like these.

**Comment by zonque** [comment]
I just tried to reproduce this after upgrading all packages, but couldn't. I consider this issue fixed, will reopen with more information as soon as it reappears. Thanks a lot!
