### ISSUE TITLE
Display git status in minimap

### ISSUE THREAD

**Issue by zonque** [atom/git-diff#67]
Not sure whether that's a request for git-diff or minimap, but it would be very useful if git diffs would also be visible in the minimap window, so developers can quickyl navigate to them.

**Comment by mnquintana** [comment]
This would be a request for minimap, but there also just so happens to be [a minimap plugin for it](https://github.com/atom-minimap/minimap-git-diff) already.

**Comment by zonque** [comment]
Awesome, thanks!
