### ISSUE TITLE
git-diff stopped working?

### ISSUE THREAD

**Issue by Gabriel-p** [atom/git-diff#69]
I have version 0.55.0 installed and it doesn't seem to work anymore. No diffs are marked in the gutter.

**Comment by izuzak** [comment]
@Gabriel-p Can you share a bit [more information](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#submitting-issues)? Does this happen in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)? Does it happen for every project or only some? Can you provide steps which reproduce the problem, starting from a `git clone` command which clones a publicly available repository?

**Comment by Gabriel-p** [comment]
If I use safe mode the extension is disabled so of course it doesn't work.

It happens for every project, but I'm seeing that apparently Atom isn't even recognizing changes in the repo.

I cloned this project and modified its README.md file. Here's what I see in Sublime (notice the marks in the gutter):

![sublime_diff](https://cloud.githubusercontent.com/assets/6054951/9493802/a1d961fe-4bd8-11e5-8d31-11647a91d0b9.png)

and here's the same file in Atom with all extensions disabled except for `git-diff`, `tabs`, `status-bar`, and `settings-view`:

![atom_no_diff](https://cloud.githubusercontent.com/assets/6054951/9493806/a63d87f2-4bd8-11e5-9967-442c098e070d.png)

**Comment by mnquintana** [comment]
> If I use safe mode the extension is disabled so of course it doesn't work.

That shouldn't be the case - safe mode only disables packages you manually installed, and git-diff is bundled with Atom. Did you manually install git-diff? Can you post a list of your installed packages? (`apm list --installed`)

**Comment by Gabriel-p** [comment]
Sorry, didn't know that.

I enabled almost all packages again (left out some languages I never use) and tried `atom --safe`. I see the same behaviour, ie: changes in the repo file are not being recognized.

Here's the list of installed packages:

````
$ apm list --installed
/home/gabriel/.atom/packages (14)
├── atom-alignment@0.12.1
├── feedback@0.38.0
├── git-plus@5.4.7
├── highlight-selected@0.10.1
├── linter@1.4.3
├── linter-pep8@1.0.1
├── linter-pylint@1.0.0
├── minimap@4.13.1
├── minimap-git-diff@4.1.8
├── monokai@0.18.0
├── save-session@0.15.7
├── script@2.26.4
├── script-runner@1.8.3
└── sublime-default-syntax@0.2.2
````

**Comment by Gabriel-p** [comment]
Well you can close this issue now. I just used `Open Folder` in Atom which opened the folder in a new instance of the app.

After closing both instances, the new one remained the "default" one en the issue is now gone. This could perhaps be related to the fact that I keep the `/.atom` folder in my Dropbox and link it into my `/home/`. A few hours ago I moved that folder and re-linked it. Perhaps the link was wrong before?

In any case, I think this issue can now be closed.
