### ISSUE TITLE
Impossible to see in a light syntax theme.

### ISSUE THREAD

**Issue by Fishrock123** [atom/git-diff#7]
[GitGutter's indicator icons](https://github.com/jisaacks/GitGutter#screenshot) are much clearer, even on a light background. 
It would be great if `git-diff` would have that sort of option.

**Comment by JaKXz** [comment]
@felixkiss I tried adding those lines to my `styles.less` files while using the [fizzy theme](https://github.com/jglovier/fizzy) but with no luck unfortunately. thanks for the base though!
