### ISSUE TITLE
Delete icon has spell-check underline

### ISSUE THREAD

**Issue by kayone** [atom/git-diff#70]
All other icons in the gutter look fine, but the delete icon has a red spelling error underneath it.

![image](https://cloud.githubusercontent.com/assets/412280/9422111/53bf9b8c-483b-11e5-93ab-e000979462e6.png)

**Comment by izuzak** [comment]
Thanks for the report -- I'm seeing that as well. Wondering if @simurai can :art:-away that line :smile:

**Comment by simurai** [comment]
The red dotted line is intended. It should make it easier to see that a line got removed. Maybe could be changed to solid to make it less like spell check.

<img width="57" alt="screen shot 2015-08-25 at 9 20 58 am" src="https://cloud.githubusercontent.com/assets/378023/9455888/e472d82a-4b0a-11e5-83c3-c0aee15553ae.png">

But something is strange with the icon in the initial screenshot. It should be a triangle and not a short 2px line (above) the dotted one.

@kayone Do you see the same when switching to other themes. The dotted line is mostly added in the One themes.

**Comment by kayone** [comment]
I see the triangle when disabling _Show Icons in Editor Gutter_


![image](https://cloud.githubusercontent.com/assets/412280/9456344/3fd96574-4a8b-11e5-8a42-65e9f0caeaa8.png)
![image](https://cloud.githubusercontent.com/assets/412280/9456352/4bfae422-4a8b-11e5-9dc4-50c2e5ff3138.png)

**Comment by simurai** [comment]
ohh.. I didn't even know that *Show Icons in Editor Gutter* exists. I guess the "something is strange with the icon" is a `minus` icon. :sweat_smile:

ok, yep.. when icons are shown, the dotted line looks wrong.

**Comment by simurai** [comment]
ok, this should be fixed in the next theme update. @kayone thanks for the issue.

**Comment by kayone** [comment]
Thank you so much for being so responsive.

**Comment by kayone** [comment]
I noticed this was fixed in https://github.com/atom/one-light-syntax when I checked other themese it seemed like they all had the same issue.

**Comment by simurai** [comment]
From the core themes, I think the dotted lines only got added to One dark and One light. Some community themes that forked from One still have it.
