### ISSUE TITLE
Option to make gutter marks more prominent

### ISSUE THREAD

**Issue by claytonrcarter** [atom/git-diff#78]
I use the colored markers in the gutter instead of the +/./- icons to save space on screen, but sometimes those skinny little markers are easy to lose track of when scrolling rapidly or glancing at the screen.  I would love an option to change the background color of the line numbers in the gutter, or maybe even the line numbers themselves.

**Comment by maxbrunsfeld** [comment]
Closing this out as per the discussion in https://github.com/atom/git-diff/pull/79.
