### ISSUE TITLE
Not showing gutter highlights on files with capital letters in the name

### ISSUE THREAD

**Issue by lee-dohm** [atom/git-diff#86]
For example `README.md` in the atom/atom repo:

![mismatch-and-errors](https://cloud.githubusercontent.com/assets/1038121/13205940/c6820a1c-d8a8-11e5-9e0d-bd3b394d84f3.png)

Of special note is in the error message it says that `readme.md` cannot be found, not `README.md`. Could it be that something is not matching the filename because of a case issue?

### Steps to Reproduce

1. Clone the https://github.com/atom/atom repository
1. Launch Atom from the Atom source directory
1. Press <kbd>Cmd+T</kbd> to open the fuzzy-finder
1. Type `README` and press <kbd>Enter</kbd>
1. Press <kbd>Enter</kbd> a few more times
1. Press <kbd>Cmd+S</kbd> to save the file

**Expected:** Tree view, tabs and gutter to all agree that the file is modified
**Actual:** Tree view and tabs show file to be modified, gutter does not

Reproduced using Atom v1.7.0-dev-e39d200 on Mac OS X 10.11.3.

**Comment by 50Wliu** [comment]
Beat me to reporting this :laughing:.

**Comment by lee-dohm** [comment]
You've got to build some snippets! I have templates and stuff for many of these things :laughing:

**Comment by lee-dohm** [comment]
Created some test files:

* `FileWithSomeCaps.txt` &mdash; Reproduced the issue
* `FILE_WITH_ALL_CAPS.txt` &mdash; Reproduced the issue
* `file_in_all_lowercase.txt` &mdash; **Does not** reproduce the issue

**Comment by joshaber** [comment]
Wow, thanks for figuring this out :heart: @lee-dohm, @50Wliu
