### ISSUE TITLE
Gutter diff icons missing

### ISSUE THREAD

**Issue by justinsolms** [atom/git-diff#87]
I have no git gutter diff icons. This corrects when I run `atom --safe`. Issue re-appears when I run atom normally.

This issue may have appeared after I installed `git-plus` and `git-control`. However I'm unsure about this. I have subsequently removed the two aforesaid packages.

Atom `1.5.3`

My platfrom: `Linux sundesk01 3.16.0-60-generic #80~14.04.1-Ubuntu SMP Wed Jan 20 13:38:16 UTC 2016 i686 i686 i686 GNU/Linux`

**Comment by justinsolms** [comment]
Solved!

I noticed I had `git-diff` listed under both `community` and `core` packages. 

The issue resolved itself after I ran
`apm uninstall git-diff`

I remember that I had installed `git-diff` a long time ago. Maybe it wasn't a `core` package back then.

**Comment by 50Wliu** [comment]
Glad to see you solved your issue @justinsolms!
