### ISSUE TITLE
Gutter not agreeing with tabs, tree-view or git (gutter is incorrect)

### ISSUE THREAD

**Issue by lee-dohm** [atom/git-diff#88]
<img width="637" alt="screen shot 2016-03-01 at 4 58 44 pm" src="https://cloud.githubusercontent.com/assets/1038121/13447473/a588bf8e-dfd0-11e5-9bf9-b904fe6be520.png">

Reproduced on Atom v1.7.0-dev-19623b3 on Mac OS X 10.11.3. It does *not* repro on either v1.5.3 or v1.6.0-beta6.

Steps I used to (unsuccessfully) correct it:

1. Close and reopen the file
1. Close and restart Atom
1. Open Atom in Safe Mode
1. Open Atom in Safe Mode with `--clear-window-state`
1. Open Atom with only `--clear-window-state`
1. Clone the repository again in a new directory and open Atom there

I'll try bisecting next to see if I can track down where it went wrong.

**Comment by joshaber** [comment]
So the tree-view was wrong but the diff markers were right? Or do I have that backwards?

**Comment by lee-dohm** [comment]
Yeah, sorry ... the diff markers were wrong. Tree view and tabs were correct.

**Comment by joshaber** [comment]
Could you zip up the repo and post it somewhere accessible? This sounds really odd.

**Comment by lee-dohm** [comment]
Yeah, I'll do that.

**Comment by lee-dohm** [comment]
Forgot to post the bisect results. This was weird enough I wasn't sure if it was necessarily a git-diff change that did it, but the bisect tracked down the first occurrence to [the update of Atom to git-diff v1.0.0](https://github.com/atom/atom/commit/e4f23d47680fd7edd45f5d3c3056d1352164c3a3).

**Comment by 50Wliu** [comment]
I can reproduce this (I think).

1. Open a file that does not have a trailing newline.
2. Save it to trigger a newline being added (and observe that the diff marker appears on the wrong line).
3. Close Atom.
4. Discard changes through Git (in my case, Github Desktop).
5. Re-open Atom.
6. Observe that the diff marker is still there despite changes being discarded.

Closing and re-opening the file does not help.

Windows 10 x64, 1.7.0-dev-663d9b2, safe mode.  The file in question has LF line endings if it matters.

**Comment by joshaber** [comment]
I've opened on nodegit with the fix: https://github.com/nodegit/nodegit/pull/938
