### ISSUE TITLE
Diff marker appears on the wrong line, if at all

### ISSUE THREAD

**Issue by 50Wliu** [atom/git-diff#89]
Steps to reproduce:
1. Open a file that does not have a trailing newline.
2. Save the file to add a trailing newline.

Expected: A green/added diff marker is added at the last line.
Actual: A yellow/modified diff marker is added a few lines before that (line 7 instead of line 10 in this case), or no diff marker appears (on a longer file that scrolls).

Of note: The line where the diff marker is showing up has some Russian characters in it.

Windows 10 x64, Atom 1.7.0-dev-663d9b2, safe mode.

/cc @joshaber

**Comment by joshaber** [comment]
I'm pretty sure this is https://github.com/atom/git-diff/issues/88, but I'll leave it open until I have a better understanding of it.
