### ISSUE TITLE
Doesn't show changes in gutter when there is a symlink in path to git repository on Windows 10

### ISSUE THREAD

**Issue by hron** [atom/git-diff#91]
Let's say we have a git repo in `E:\src\project` and there is a symlink to src in home folder `C:\Users\aleks\src -> E:\src`.

git-diff works without problems when Atom opens target directory `E:\src\project`, but when Atom tries to open this project using the symlink, i.e. `C:\Users\aleks\src\project` git-diff doesn't show changes in the gutter.

However, tree-view always shows the changes. Atom also shows branch name in the status bar in both cases.

**Comment by florianb** [comment]
This bug seems to be OS unspecific - i am using Mac OS X:

```
Error getting line diffs for /Users/florianb/github/linter-javac/spec/sym-fixtures/sub-directory/Test.java:(anonymous function) @ /Users/florianb/github/atom/node_modules/git-diff/lib/git-diff-view.coffee:172
/Users/florianb/github/atom/node_modules/git-diff/lib/git-diff-view.coffee:173
Error: the path 'sym-fixtures' exists but is not a tree(…)(anonymous function) @ /Users/florianb/github/atom/node_modules/git-diff/lib/git-diff-view.coffee:173

apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.10
git 2.7.4
```

**Comment by steve2507** [comment]
I have the same issue with drive mappings to a Windows share. Not sure if I should open a new issue for that, as it may very well be related.

**Comment by notnyt** [comment]
I'm seeing the same issue when opening a project via webdrive.

**Comment by maxbrunsfeld** [comment]
A lot has changed since we've heard about this, and I can't reproduce it on mac os. So the issue  may have been fixed. If not, please feel free to open a new issue on [the main Atom repository](https://github.com/atom/atom), as we have [moved this code there](https://github.com/atom/atom/pull/17993). Thanks!
