### ISSUE TITLE
Broken for submodules since 1.0.0 (async Git?)

### ISSUE THREAD

**Issue by kankaristo** [atom/git-diff#97]
`git-diff` stopped working with a recent update. It could have been version 1.0.0, which apparently started using async Git? I'm currently using 1.0.1 and Atom 1.7.0-beta0 (on Ubuntu 15.10).

The diff markers are working in normal/non-submodule repositories, but for diffs in a submodule, I'm getting the following errors in the console:
```
Error getting line diffs for /home/sami/IndiumGames/Infamis/engine/src/assetmanager_model.cpp:
    (anonymous function) @ /usr/share/atom-beta/resources/app.asar/node_modules/git-diff/lib/git-diff-view.js:172

Error: the path 'engine' exists but is not a tree
    at Error (native)
    (anonymous function) @ /usr/share/atom-beta/resources/app.asar/node_modules/git-diff/lib/git-diff-view.js:173
```

`Infamis` is the main repository (and project root directory), `engine` is the submodule's path, and the file I'm trying to see diffs for is `engine/src/assetmanager_model.cpp`.

This is also happening with `--safe`, and with all custom styles, init scripts, etc. disabled.

**Comment by joshaber** [comment]
Thanks for letting us know @kankaristo! This'll be fixed in 1.6.1.
