### ISSUE TITLE
Diffs not updating after commit using patch

### ISSUE THREAD

**Issue by Bouzmine** [atom/git-diff#98]
When I commit only part of a file using `git --patch [file]`, the file won't update its diffs unless I close it and open it again.

**Comment by maxbrunsfeld** [comment]
A lot has changed since we've heard about this happening, so the issue  may have been fixed. If not, please feel free to open a new issue on [the main Atom repository](https://github.com/atom/atom), as we have [moved this code there](https://github.com/atom/atom/pull/17993). Thanks!
