### ISSUE TITLE
Error: Reference 'refs/heads/master' not found

### ISSUE THREAD

**Issue by download13** [atom/git-diff#99]
Got this error in the console:
![Console screenshot](http://i.imgur.com/YhpuK9X.png)

I noticed that the diff markers are not appearing next to the line numbers in files. Not sure if that has anything to do with it.

**Comment by 50Wliu** [comment]
@download13 Please read [How do I submit a (good) bug report]](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) and include the relevant information here so that we can triage this further.  Thanks!

**Comment by download13** [comment]
Nevermind, those errors were caused by Atom code, which is no longer in that repo anyway.
